#!/bin/bash -e
#
# Cross compile QEMU with mingw toolchain on Linux.
#
# Copyright (c) 2016 Red Hat Inc.
#
# Authors:
#  Fam Zheng <famz@redhat.com>
#
# This work is licensed under the terms of the GNU GPL, version 2
# or (at your option) any later version. See the COPYING file in
# the top-level directory.

. common.rc

requires_binary x86_64-w64-mingw32-gcc
requires_binary i686-w64-mingw32-gcc

cd "$BUILD_DIR"
TARGET_LIST=xtensa-softmmu
#'--cross-prefix=x86_64-w64-mingw32-' '--target-list=xtensa-softmmu' '--disable-capstone' '--enable-gtk' '--enable-sdl' '--disable-vnc'
#for prefix in x86_64-w64-mingw32- i686-w64-mingw32-; do
#    TARGET_LIST=${TARGET_LIST:-$DEF_TARGET_LIST} \
        build_qemu --cross-prefix=x86_64-w64-mingw32- \
        --disable-capstone \
        --enable-gtk \
        --enable-sdl \
        --disable-vnc
x86_64-w64-mingw32-strip /tmp/qemu-test/build/xtensa-softmmu/qemu-system-xtensaw.exe
cp /tmp/qemu-test/build/xtensa-softmmu/qemu-system-xtensaw.exe /mnt/windows
#    install_qemu
#    make installer
#    make clean
#done
